sudo: false
language: node_js
node_js:
  - 14
install:
  - npm install mocha
  - npm install chai
  - npm install
script:
  - mocha
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT