sudo: false
language: node_js
node_js:
  - 14
install:
  - npm install mocha
  - npm install chai
	- npm install istanbul@1.1.0-alpha.1 --save-dev
  - npm install c8 -g
	- npm install
script:
  - npx c8 mocha