# reference: https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions
name: STproject2022-github-actions
run-name: testing if the codes pass
on: [push]
jobs:
  STproject2022-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: sudo npm install
      - run: npm test
